services:
  db:
    container_name: mecha_db_test
    image: mysql
    restart: always
    ports:
      - "6666:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chat_application
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - type: bind 
        source: ./db
        target: /docker-entrypoint-initdb.d