#name: mecha
services:
  db:
    container_name: mecha_dbb
    # mysql -u user -p"1234" chat_application
    image: mysql
    restart: always
    ports:
      - "4321:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chat_application
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - type: bind 
        source: ./db
        target: /docker-entrypoint-initdb.d
